catch a fs error causing app crash.
Error: ENOENT: no such file or directory, stat '***/0000185180.jpg'
    at Object.fs.statSync (fs.js:948:11)
    at FSWatcher.<anonymous> (***/node_modules/hound/hound.js:55:20)
    at emitTwo (events.js:126:13)
    at FSWatcher.emit (events.js:214:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1364:12)
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '***/0000185180.jpg'